name: "SonarQube Scanner Trigger"
author: "Fede Calendino"
description: "Automatically trigger a call to sonnar-scanner."
inputs:
  url:
    description: "SonarQube server URL"
    required: true
    default: "."
  token:
    description: "Authentication token for SonarQube"
    required: true
    default: "."  
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "radio"
  color: "blue"
